dags/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
#from django.conf.urls import url, include

from dags import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^login/$', views.login),
    re_path(r'^exchange/$', views.exchange),
    re_path(r'^register/$', views.register),
    re_path(r'^rest_register/$', views.rest_register),
    re_path(r'^rest_login/$', views.rest_login),
    re_path(r'^rest_logout/$', views.rest_logout),
    re_path(r'^logout/$', views.logout),
    re_path(r'^get_user_info/$', views.get_user_info),
    re_path(r'^pipeline/', include('horae.urls')),
    re_path(r'^processor/', include('horae.processor_urls')),
    re_path(r'^picker/', include('picker.urls')),
    re_path(r'^pyplugin/', include('pyplugin.urls')),
    re_path(r'^dagschedule/', include('dagschedule.urls')),
    re_path('rest_token/', TokenObtainPairView.as_view()),
    re_path('rest_refresh/', TokenRefreshView.as_view())

]

dagschedule/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from dagschedule import views

urlpatterns = (
    re_path(r'^$',views.dagschedule),
    re_path(r'^pipeline/', views.dagschedule),
    re_path(r'^processor/', views.processor),
    re_path(r'^picker/', views.picker),
    re_path(r'^history/', views.history),
)

horae/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from horae import views

urlpatterns = (
    re_path(r'^$',views.noah_index),
    re_path(r'^index/$',views.noah_index),
    re_path(r'^(?P<pipe_id>\d+)/$', views.detail),
    re_path(r'^get_project_tree/$', views.get_project_tree),
    re_path(r'^search_pipeline/$', views.search_pipeline),
    re_path(r'^search_all_pipeline/$', views.search_all_pipeline),
    re_path(r'^search_task/$', views.search_task),
    re_path(r'^get_project_tree_async/$', views.get_project_tree_async),
    re_path(r'^get_pipeline_detail/$', views.get_pipeline_detail),
    re_path(r'^get_tasks/$', views.get_tasks),
    re_path(r'^get_task_detail/(?P<task_id>\d+)/$', views.get_task_detail),
    re_path(r'^unlink_task/$', views.unlink_task),
    re_path(r'^link_task/$', views.link_task),
    re_path(r'^update/(?P<pipe_id>\d+)/$', views.update),
    re_path(r'^copy_pipeline/$',views.copy_pipeline),
    re_path(r'^delete/(?P<pipe_id>\d+)/$', views.delete),
    re_path(r'^update_task/(?P<task_id>\d+)/$', views.update_task),
    re_path(r'^task_md_result/(?P<task_id>\d+)/$', views.task_md_result),
    re_path(r'^update_block/(?P<hash>.*)/$', views.update_block),
    re_path(r'^get_pipelines/$',views.get_pipelines),
    re_path(r'^get_server_tags/$', views.get_server_tags),
    re_path(r'^create_task/(?P<pipe_id>\d+)/$', views.create_task),
    re_path(r'^create/$', views.create),
    re_path(r'^get_user_list/$', views.get_user_list),
    re_path(r'^get_pipeline_with_project_tree/$', views.get_pipeline_with_project_tree),
    re_path(r'^history/$',views.history),
    re_path(r'^history_list/(?P<order_info>\w+)/$', views.history_list),
    re_path(r'^history/getlog/(?P<id>\d+)/$', views.get_task_information),
    re_path(r'^run_tasks/$', views.run_tasks),
    re_path(r'^history/(?P<pipe_id>\d+)/$', views.historypipe),
    re_path(r'^in_history/(?P<pipe_id>\d+)/$', views.in_historypipe),
    re_path(r'^get_params/$', views.get_params),
    re_path(r'^delete_task/(?P<pipe_id>\d+)/$', views.delete_task),
    re_path(r'^add_new_project/$', views.add_new_project),
    re_path(r'^update_project/$', views.update_project),
    re_path(r'^get_message/$', views.get_message),
    re_path(r'^get_status_graph/$', views.get_status_graph),
    re_path(r'^get_graph/$', views.get_graph),
    re_path(r'^get_task_log/$', views.get_all_log_list),
    re_path(r'^get_log_content/$', views.get_log_content),
    re_path(r'^get_tail/$', views.get_tail),
    re_path(r'^download/(?P<args>.*)/$', views.big_file_download),
    re_path(r'^run_one_task/$', views.run_one_task),
    re_path(r'^run_one_pipeline/$', views.run_all_pipeline),
    re_path(r'^stop_task/$', views.stop_task),
    re_path(r'^run_task_with_all_successors/$', views.run_task_with_all_successors),
    re_path(r'^history/set_task_success/$', views.set_task_success),
    re_path(r'^run_some_task/$', views.run_some_task),
    re_path(r'^get_retry_history_list/$', views.get_retry_history_list),
    re_path(r'^on_line/$', views.on_line),
    re_path(r'^port_filter/$', views.port_filter),
    re_path(r'^futures_index/(?P<pipe_id>\d+)/$', views.futures_index),
    re_path(r'^futures_datas/$', views.futures_datas),
    re_path(r'^create_edge/$', views.create_edge),
    re_path(r'^update_edge/$', views.update_edge),
    re_path(r'^copy_task/$', views.copy_task),
    re_path(r'^copy_pipeline/$',views.copy_pipeline),
    re_path(r'^pindex/$',views.pindex),
    re_path(r'^liviz_index/$',views.liviz_index),
    re_path(r'^show_block/(?P<hash>.*)/$',views.show_block),
    re_path(r'^getDatas/$',views.get_datas),

    re_path(r'^update_pipline_graph/(?P<pipe_id>\d+)/$', views.update_pipline_graph),
    re_path(r'^get_power_nodes/$', views.get_power_nodes),
    re_path(r'^run_history/$', views.run_history),
    re_path(r'^get_package_list/$', views.get_package_list),
    re_path(r'^get_package_content/$', views.get_package_content),
    re_path(r'^download_package/(?P<args>.*)/$', views.download_package),

    re_path(r'^compile_solidity/$', views.compile_solidity),
    re_path(r'^deploy_solidity/$', views.deploy_solidity),
    re_path(r'^set_gas_prepayment/$', views.set_gas_prepayment),
    re_path(r'^call_function_solidity/$', views.call_function_solidity),
    re_path(r'^query_function_solidity/$', views.query_function_solidity),
    re_path(r'^get_statistics/$', views.get_statistics),
    re_path(r'^set_pipeline_server_tag/$', views.set_pipeline_server_tag),

    re_path(r'^get_global_overview_data/$', views.get_global_overview_data),
    re_path(r'^get_realtime_trade_stats/$', views.get_realtime_trade_stats),
    re_path(r'^get_data_market_overview/$', views.get_data_market_overview),
    re_path(r'^get_data_category_stats/$', views.get_data_category_stats),
    re_path(r'^get_data_detail_list/$', views.get_data_detail_list),
    # 算力大盘数据接口
    re_path(r'^get_compute_market_overview/$', views.get_compute_market_overview),
    # 算力分类统计接口
    re_path(r'^get_compute_category_stats/$', views.get_compute_category_stats),
    # 算力详情明细接口
    re_path(r'^get_compute_node_details/$', views.get_compute_node_details),
    # 模型大盘数据接口
    re_path(r'^get_model_market_overview/$', views.get_model_market_overview),
    # 模型分类统计接口
    re_path(r'^get_model_category_stats/$', views.get_model_category_stats),
    # 模型详情列表接口
    re_path(r'^get_model_asset_details/$', views.get_model_asset_details),
)

horae/forms.py
#coding=utf-8
import re
from django import forms
from django.forms import ModelForm
from horae.models import Pipeline,Processor,Task

class PipelineForm(ModelForm):
    error_messages = {
        'duplicate_path': '此路径已存在！',
        'invalid': '流程名称为字母、数字、下划线！',
    }

    name = forms.CharField(
            label='流程名称',
            widget = forms.TextInput(attrs={'class':'form-control',
                'placeholder':'输入任务名称，格式依照“行业类目_项目_功能”'
                }),
            error_messages={
                'required':'流程名称不能为空！',
                'unique':'流程名称重复！',
                'invalid': '流程名称为字母、数字、下划线！',}
            )

    ct_time = forms.CharField(
            label='调度时间',
            widget= forms.TextInput(attrs={'class':'form-control',
                'placeholder':'crontab格式，如:10 * * * * 表示每小时10分运行一次'
                }),
            required = False)
    
    principal = forms.CharField(
            label='负责人',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required = False)

    tag = forms.CharField(
            label='应用分组',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required = False)

    project_id = forms.IntegerField(
            label='所属项目',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required = False)

    life_cycle = forms.CharField(
            label='有效期至',
            widget = forms.TextInput(attrs={'class':'form-control',
                'placeholder':'设置生命周期，会自动删除流程，最大生命周期为6个月'
                }),
            error_messages={
                'required':'生命周期不能为空！'}
            )

    description = forms.CharField(
            label='描述',
            widget = forms.Textarea(attrs={'class':'form-control',
                'cols': 80, 'rows': 5,
                'placeholder':
                '请详细填写流程的功能描述信息'
                }),
            required=False) 

    send_mail = forms.BooleanField(label='邮件',required=False,
            initial=True)
    send_sms = forms.BooleanField(label='钉钉',required=False) 
    monitor_way = forms.IntegerField(
            label='报警方式',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required = False)
    type = forms.IntegerField(
            label='流程类型',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required = False)
    enable = forms.BooleanField(label='上下线',required=False) 
    class Meta: 
        model = Pipeline
        fields = ('name' , 'ct_time','principal','tag','description',
                'send_mail','send_sms','life_cycle', 'monitor_way', 'type', 'enable')


class ProcessorForm(ModelForm):
    error_messages = {
        'invalid': '流程名称为字母、数字、下划线！',
    }

    TYPE_STREAM_DATA = -1
    TYPE_SCRIPT = 1
    TYPE_SPARK = 2
    TYPE_OOZIE = 3
    TYPE_ODPS = 4
    TYPE_SHELL = 5
    TYPE_DOCKER = 6
    TYPE_CLICKHOUSE = 7
    TYPE_V100 = 8
    type_choices = (
        (TYPE_STREAM_DATA, 'stream_data'),
        (TYPE_SCRIPT, 'python'),
        (TYPE_SPARK, 'spark'),
        (TYPE_OOZIE, 'oozie'),
        (TYPE_ODPS, 'odps'),
        (TYPE_SHELL, 'shell'),
        (TYPE_DOCKER, 'docker'),
        (TYPE_CLICKHOUSE, 'clickhouse'),
        (TYPE_V100, 'v100')
    )
    
    type = forms.ChoiceField(label='算子类型',
            choices = type_choices,
            widget= forms.Select(attrs={'class':'form-control',
                'style':'width:100px',
                }),
            initial=TYPE_SCRIPT
            )

    name = forms.CharField(
            label='算子名称',
            widget = forms.TextInput(attrs={'class':'form-control',
                'placeholder':'请使用字母、数字、下划线',
                'style':'width:303px'
                }),
            error_messages={
                'required':'算子名称不能为空！',
                'unique':'算子名称重复！',
                'invalid': '算子名称为字母、数字、下划线！',}
            )
    principal = forms.CharField(
            label='负责人',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required = False)

    config = forms.CharField(
            label='参数配置',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            error_messages={
                'required':'参数模板不能为空！',}
            )

    template = forms.CharField(
            label='执行脚本',
            widget = forms.Textarea(attrs={'class':'form-control',
                'cols': 80, 'rows': 5,
                'placeholder':
                '执行脚本模板',
                }),
            required=False) 

    description = forms.CharField(
            label='描述',
            widget = forms.Textarea(attrs={'class':'form-control',
                'cols': 80, 'rows': 5,
                'style':'margin-left:14px',
                'placeholder':
                '请详细填写算子的功能描述信息'
                }),
            required=False) 
    
    tag = forms.CharField(
            label='标签',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required = False)


    class Meta: 
        model = Processor
        fields = ('name','type','template','config','description','tag')

class TaskForm(ModelForm):
    error_messages = {
        'invalid': '任务名称为字母、数字、下划线！',
    }

    TYPE_STREAM_DATA = -1
    TYPE_SCRIPT = 1
    TYPE_SPARK = 2
    TYPE_OOZIE = 3
    TYPE_ODPS = 4
    TYPE_SHELL = 5
    TYPE_DOCKER = 6
    TYPE_CLICKHOUSE = 7
    TYPE_V100 = 8
    type_choices = (
        (TYPE_STREAM_DATA, 'stream_data'),
        (TYPE_SCRIPT, 'python'),
        (TYPE_SPARK, 'spark'),
        (TYPE_OOZIE, 'oozie'),
        (TYPE_ODPS, 'odps'),
        (TYPE_SHELL, 'shell'),
        (TYPE_DOCKER, 'docker'),
        (TYPE_CLICKHOUSE, 'clickhouse'),
        (TYPE_V100, 'v100')
    )

    LEVEL_ONE = 5
    LEVEL_TWO = 6
    LEVEL_THREE = 7
    LEVEL_FOUR = 8
    LEVEL_FIVE = 9
    LEVEL_SIX = 10

    priority_choice = (
        (LEVEL_TWO, 'P4'),
        (LEVEL_THREE, 'P3'),
        (LEVEL_FOUR, 'P2'),
        (LEVEL_FIVE,'P1'),
        (LEVEL_SIX,'P0')
    )

    NOT_RETRY = 1
    ONE_TIME = 2
    FIVE_TIME = 3
    ALWAYS = 4
    retry_choice = (
        (NOT_RETRY, '不重试'),
        (ONE_TIME, '1次'),
        (FIVE_TIME, '5次'),
        (ALWAYS, '一直'),
    )
    
    type = forms.ChoiceField(label='任务类型',
            choices = type_choices,
            widget= forms.Select(attrs={'class':'form-control',
                'style':'width:129px',
                }),
            initial=TYPE_SCRIPT,required=False)

    use_processor = forms.BooleanField(label='选择算子',required=False,
            initial=False)

    name = forms.CharField(
            label='任务名称',
            widget = forms.TextInput(attrs={'class':'form-control',
                'placeholder':'请输入任务名称',
                'style':'width:474px',
                }),
            error_messages={
                'required':'任务名称不能为空！',
                'unique':'任务名称重复！',
                'invalid': '任务名称为字母、数字、下划线！',}
            )
    

    config = forms.CharField(
            label='任务参数',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required=False)

    template = forms.CharField(
            label='执行脚本',
            widget = forms.Textarea(attrs={'class':'form-control',
                'cols': 80, 'rows': 5,
                'placeholder':
                '执行脚本模板',
                'style':'width:720px',
                }),
            required=False) 

    processor_id = forms.CharField(
            label='算子id',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required=False)

    prev_task_ids = forms.CharField(
            label='依赖ids',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required=False)

    retry_count = forms.ChoiceField(label='失败重复次数',
            choices = retry_choice,
            widget= forms.Select(attrs={'class':'form-control',
                'style':'width:150px',
                }),
            initial=NOT_RETRY
            ) 
    
    over_time = forms.IntegerField(
            label='超时报警时间',
            widget = forms.TextInput(attrs={'class':'form-control',
                'style':'width:155px',
                'placeholder':'单位：秒'
                }),
            required=False)


    description = forms.CharField(
            label='描述',
            widget = forms.Textarea(attrs={'class':'form-control',
                'cols': 80, 'rows': 5,
                'placeholder':'请说明任务的基本功能及用途',
                'style':'width:720px; margin-left:15px;',
                }),
            required=False) 

    priority = forms.ChoiceField(label='优先级',
            choices = priority_choice,
            widget= forms.Select(attrs={'class':'form-control',
                'style':'width:150px',
                }),
            initial=LEVEL_ONE
            ) 

    server_tag = forms.CharField(
            label='机器标签',
            widget = forms.TextInput(attrs={'class':'form-control',
                'type':'hidden'}),
            required=False)

    class Meta: 
        model = Task
        fields = ('name','type','config','template','processor_id',\
                'prev_task_ids','description','retry_count','over_time',\
                'priority','server_tag')

#upload file
class DocumentForm(forms.Form):
    docfile = forms.FileField(
            label = 'Select a file'
            )

horae/templates/liviz_js.html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="Content-Style-Type" content="text/css" />
		<meta http-equiv="Content-Script-Type" content="text/javascript" />
	    <link rel="stylesheet" type="text/css" href="/static/liviz/jsviz.css"></link>

		<script type="text/javascript" src="/static/liviz/js/workered-jsviz.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/jquery.js"></script>
		<script type="text/javascript" src="/static/liviz/js/progress-view.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/progress-model.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/worker-stopgo.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/global-util.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/jsviz.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/errorsink.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/jsviz-ui.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/graph-model.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/curve-tween.js?v=2"></script>
		<script type="text/javascript" src="/static/liviz/js/difftype.js?v=2"></script>
		<title>Liviz.js (JSViz)</title>
	</head>
	<body class="app-page" onload="void w_launch()">
		<svg id="graph-svg" style="outline: none;" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="mainGraphContainer" /></svg>
		<div id="coding-area">
			<img alt="Liviz.js" src="images/livizlogo.png" /><br />
			<textarea id="dot-src" style="width: 260px;height: 300px;">
digraph testgraph{
 {node[shape=none,
       fontsize=23]
  "Welcome to Liviz.js!"
 }
 {node[shape=none]
  "Interactive GraphViz on your browser"
 }
 {edge[color=transparent]
  "Welcome to Liviz.js!" ->
  "Interactive GraphViz on your browser"
 }
 
 A -> B -> C -> D -> E;
 B -> D;
 
 {node[shape=box];
   1 -> 2 -> 3;
 }
 
 E -> 1;2 -> C;
 {rank=same; 1; A;}
 {rank=same; 3; D;}
}

			</textarea> <button id="test-button" style="font-size:40%; position: relative; left: -7em; top: -1em;">Test</button>
			<div id="dot-options">
				<ul>
					<li id="cmd-prog">Show progress</li>
					<li id="cmd-slow">Run slowly</li>
					<li id="cmd-demo">Take a tour</li>
					<li id="cmd-about">About...</li>
				</ul>
			</div>
		</div>
	</body>
</html>

horae/templates/update_pipeline.html
{% extends "base_iframe.html" %}
{% block content %}
{% load static %}
{% load horae_filter %}
<div id="page-wrapper" style="margin: 0 0 0 0;padding-top: 0px;">
    <p style="color:red;display:none" id="error"></p>
    <div class="col-lg-10 col-lg-offset-1">
        <form action="" method="post" id="update_pipeline_form" class="all_form" style="margin-left:70px" autocomplete="off">
            <fieldset>
                <input type="hidden" id="project_id_hidden_manual" name="variable" value="{{ pipeline.project_id}}">
                <input type="hidden" id="pipe_principal" name="variable" value="{{ pipeline.owner_id_list }}">
                <input type="hidden" id="pipe_monitor_way" name="variable" value="{{ pipeline.monitor_way }}">
                <div class="form-group">
                    <label>
                        <font color="red">*</font>
                        {{ form.name.label }}:
                    </label>
                    {{ form.name }}
                    <span style="color:#9aa0af;">流程的标记名称，方便流程的管理区分</span>
                </div>
                <div class="form-group">
                    <label>
                        {{ form.ct_time.label }}:
                    </label>
                    {{ form.ct_time }}
                    <span style="color:#9aa0af;">crontab格式，如:10 * * * * 表示每小时10分运行一次</span>
                </div>

                <div class="form-group">
                    <label style="margin-right:10px">
                        负责人:
                    </label>
                    <script type="text/javascript" src="{% static 'js/common/select2.min.js' %}"></script>
                    <script type="text/javascript" src="{% static 'js/common/form_components.js' %}"></script>
                    <link href="{% static 'css/select2.css' %}" rel="stylesheet" type="text/css" />
                    <select id="principal" style="width:500px" class="select2-select-00 full-width-fix" multiple="multiple"></select>
                    {{ form.principal }}
                </div>
                <div class="form-group">
                    <label>
                        报警方式:
                    </label>

                    <label class="checkbox-inline">
                        {{ form.send_mail }}邮件
                    </label>
                    <label class="checkbox-inline">
                        {{ form.send_sms }}钉钉
                    </label>
                    <span style="margin-left:335px;color:#9aa0af;">如需钉钉报警请设置注册时设置</span>
                </div>
                <div class="form-group">
                    <label>
                        {{ form.life_cycle.label }}:
                    </label>
                    {{ form.life_cycle }}
                    <span style="color:#9aa0af;">配置流程的生命周期，会定期清理流程</span>
                </div>
                <div class="form-group" id="project_id">
                    <label>
                        {{ form.project_id.label }}:
                    </label> &nbsp;&nbsp;
                    <input class="easyui-combotree" id="create_pipeline_project_id"
                           data-options="url:'/pipeline/get_project_tree/',method:'get'"
                           style="width: 499px;">
                </div>

                <div class="form-group" style="margin-top: 25px;">
                    <label class="textarea_label">
                        {{ form.description.label }}:
                    </label>
                    {{ form.description }}
                </div>
            </fieldset>
            <div style="margin-left:80px">
                <img id="update_busy_icon" src="{% static 'images/busy.gif' %}" style="display:none;">
                <input type="button" value="保存" id="update_pipeline_btn" onclick='updatePipe({{pipeline.id}})'
                       class="btn btn-primary pipe_btn" style="margin-left:10px" />
                <a href="javascript:void(0)" onclick="$('.modal_iframe', window.parent.document).hide();$('.modal-backdrop', window.parent.document).remove();">取消配置</a>
            </div>
        </form>
    </div>
    <div style="clear:both"></div>
</div>
<div class="modal fade" id="copyModal" tabindex="1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document" style="width:500px">
        <div class="modal-content">
            <div class="modal-header">
                <span>消息</span>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <font class="modal-title a-title-font" id="myGeneralTitle"></font>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary pipe_btn" data-dismiss="modal" aria-hidden="true" onclick="hrefindex()">确定</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="messageModal" tabindex="1" role="dialog" aria-labelledby="messageLabel">
    <div class="modal-dialog" role="document" style="width:500px">
        <div class="modal-content">
            <div class="modal-header">
                <span>消息</span>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary pipe_btn" data-dismiss="modal" aria-hidden="true">确定</button>
            </div>
        </div>
    </div>
</div>
<script>

    var reportTo = "";
    var url = "/pipeline/get_user_list/";
    $.ajax({
        type : "post",
        url  : url,
        async: false,
        dataType:"json",
        success : function(result) {
            if(result.status){
                alert(result.msg);
            }else{
                users = result.user_list;
                for(i = 0;i<users.length;i++){
                    reportTo += "<option value='"+users[i].id+"' >"+
                    users[i].name+"</option>";
                }
            }
            $("#principal").append(reportTo);
        }
    });

    var principal = [{{pipeline.principal_id_list}}]
    $("#principal").val(principal);
    var monitor_way = {{pipeline.monitor_way}};

    switch(monitor_way){
        case -1:
            $("#id_send_mail").prop("checked",false);
            $("#id_send_sms").prop("checked",false);
            break;
        case 0:
            $("#id_send_mail").prop("checked",true);
            $("#id_send_sms").prop("checked",false);
            break;
        case 1:
            $("#id_send_mail").prop("checked",false);
            $("#id_send_sms").prop("checked",true);
            break;
        case 2:
            $("#id_send_mail").prop("checked",true);
            $("#id_send_sms").prop("checked",true);
            break;
    }
</script>
<link href="{% static 'css/bootstrap-combobox.css' %}" rel="stylesheet" type="text/css">
<script type="text/javascript" src="{% static 'js/common/bootstrap-combobox.js' %}"></script>
<link href="{% static 'css/pipeline.css' %}" rel="stylesheet" type="text/css">
<script type="text/javascript" src="{{ "/static/js/pipeline/update_pipeline.js"|file_time_stamp }}"></script>
{% endblock %}